### PR TITLE
Update schema-salad to 4.5

### PR DESCRIPTION
**Pull request by pvanheus**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pvanheus** [comment]
@conda-forge-admin

**Comment by pvanheus** [comment]
This PR:
1. Updates to version 4.5.20190815125611
2. Make `future` a dependency for all Python versions (due to an error in testing with Python 2.7)

**Comment by pvanheus** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
@croth1 Could you merge this? I need it for a PR on bioconda.

**Comment by croth1** [comment]
Sorry for the delay, just arrived back home from traveling! LGTM! Thanks @pvanheus!

**Pull request merged**
