### PR TITLE
Sync cachentrol dependency with upstream.

### PR DESCRIPTION
**Pull request by johanneskoester**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Without this change, schema-salad causes currently the following error in cwltool:
```
Traceback (most recent call last):
  File "/home/johannes/.local/opt/miniconda3/envs/cwltool-test/bin/cwltool", line 11, in <module>
    sys.exit(run())
  File "/home/johannes/.local/opt/miniconda3/envs/cwltool-test/lib/python3.6/site-packages/cwltool/main.py", line 907, in run
    sys.exit(main(*args, **kwargs))
  File "/home/johannes/.local/opt/miniconda3/envs/cwltool-test/lib/python3.6/site-packages/cwltool/main.py", line 557, in main
    _logger.info(versionfunc())
  File "/home/johannes/.local/opt/miniconda3/envs/cwltool-test/lib/python3.6/site-packages/cwltool/utils.py", line 48, in versionstring
    pkg = pkg_resources.require("cwltool")
  File "/home/johannes/.local/opt/miniconda3/envs/cwltool-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/johannes/.local/opt/miniconda3/envs/cwltool-test/lib/python3.6/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (CacheControl 0.12.5 (/home/johannes/.local/opt/miniconda3/envs/cwltool-test/lib/python3.6/site-packages), Requirement.parse('CacheControl<0.12,>=0.11.7'), {'schema-salad'})
```

### CODE REVIEW

**Comment by johanneskoester** [comment]
@conda-forge-admin, please rerender

**Comment by johanneskoester** [comment]
@conda-forge-admin, please rerender

**Comment by johanneskoester** [comment]
As far as I know, getting an old version just requires to create a branch in the feedstock. No need to revert anything.

**Comment by croth1** [comment]
Thanks @johanneskoester!

Two more things:
(1) Since you are very active in the workflow manager business, do you want to add yourself to the maintainers?
(2) Did I get it right that we eventually have to add the other upper limit pins as well or risk getting this error again in the future when higher versions of those packages get uploaded? If so I think we should do that proactively - I might have time to do that on the weekend.

**Comment by johanneskoester** [comment]
I hope I don't have to touch this again, but I will when I do the next PR. Thanks for the invitation. The upper limits should always be in sync with upstream. Hence, we should ensure the following for the latest schema salad:
```
install_requires = [
    'setuptools',
    'requests >= 1.0',
    'ruamel.yaml >= 0.12.4, < 0.16',
    'rdflib >= 4.2.2, < 4.3.0',
    'rdflib-jsonld >= 0.3.0, < 0.5.0',
    'mistune >= 0.8.1, < 0.9',
    'CacheControl >= 0.11.7, < 0.12',
    'lockfile >= 0.9',
    'six >= 1.8.0',
    'typing-extensions']
```

**Comment by johanneskoester** [comment]
Would be great if you could update that, indeed! Thanks.

**Pull request merged**
